name: Xamarin.iOS

on: [push]

jobs:
  Build:
    name: Build 🛠

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10
    
    - name: Set default Xcode 12.4
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore ./UITestDemo.sln

    - name: Build
      run: msbuild ./iOS/UITestDemo.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: iOS Simulator App
        path: ${{GitHub.Workspace}}/iOS/bin/iPhoneSimulator/Debug/UITestDemo.app
