name: IOS CI/CD

on: [workflow_dispatch]

jobs:

  build: 
   
    runs-on: macos-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Folder for certificates and profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates/
          
      - name: Get Certifcate
        id: certfile
        uses: timheuer/base64-to-file@v1
        with:
         fileName: 'certificate.p12'
         encodedString: ${{ secrets.P12_BASE64 }}
         
      - name: Copy Certificate
        run: mv ${{ steps.certFile.outputs.filePath }} ~/Library/MobileDevice/Certificates/certificate.p12
        
      - name: Get Profile
        id: profile
        uses: timheuer/base64-to-file@v1
        with:
         fileName: 'decodefile.mobileprovision'
         encodedString: ${{ secrets.IOS_MOBILEPROVISION }}
       
      - name: Copy Profile
        run: mv ${{ steps.profile.outputs.filePath }} ~/Library/MobileDevice/Provisioning\ Profiles/decodefile.mobileprovision
      
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install python dependencies
        run:  python -m pip install codemagic-cli-tools
        
      - name: Intialize Keychaiin with Certificate
        run: |
          keychain initialize
          keychain add-certificates --certificate ~/Library/MobileDevice/Certificates/certificate.p12 --certificate-password ${{ secrets.P12_PASSWORD }}
      
      - name: Flutter install
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.20.0'
      - run: flutter pub get
      
      - name: Building IPA
        run: |
          xcode-project use-profiles
          flutter build ios --release --no-codesign
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release
           
      - name: upload ipa artifacts
        uses: actions/upload-artifact@v2
        with:
         name: new-ipa
         path: build/ios/ipa/*.ipa
 
  DeployApp:
    
    name: Deploy to App Center
    runs-on: ubuntu-latest
    needs: build
   
    steps:
       - name: Download a Build Artifact
         uses: actions/download-artifact@v2.0.8
         with:
          name: new-ipa
          path: ${{github.workspace}}/NBDashboardIpa
          
       - name: upload artefact to App Center
         uses: wzieba/AppCenter-Github-Action@v1
         with:
          appName: ${{secrets.APP_CENTER_APPNAME_IOS}}
          token: ${{secrets.APP_CENTER_TOKEN_IOS}}
          group: ${{secrets.APP_CENTER_GROUP_IOS}}
          file: /home/runner/work/NBDashboard/NBDashboard/NBDashboardIpa/NBDashboard.ipa
          notifyTesters: true
          debug: false   
  
  PublishIpa:

    name: Deploy to App Stor
    runs-on: macos-latest
    needs: build
    steps: 
    
       - name: Download a Build Artifact
         uses: actions/download-artifact@v2.0.8
         with:
          name: new-ipa
          path: ${{github.workspace}}/NBDashboardIpa
          
       - name: Upload app to App Store Connect
         env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.IOS_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.IOS_PASSWORD }}
         run: |
          xcrun altool --upload-app -t ios -f "/Users/runner/work/NBDashboard/NBDashboard/NBDashboardIpa/NBDashboard.ipa" -u "${{ secrets.IOS_USERNAME }}" -p "${{ secrets.IOS_PASSWORD }}"  
